package server;

public class BrickState {
	public int time, controlPower, disturbPower, angle;
	public double disturbSpeed;
	
	public BrickState(int time, double disturbSpeed, int disturbPower, int controlPower, int angle) {
		this.time = time; 					// total elapsed time
		this.disturbSpeed = disturbSpeed;
		this.disturbPower = disturbPower;
		this.controlPower = controlPower; 	// power of the measured wheel
		this.angle = angle; 				// angle of the arm
	}
	
	public String toString() {
		return "" + time +  '\t' + disturbSpeed + '\t' + disturbPower + '\t' + controlPower + '\t' + angle;
	}
	
	// generated by eclipse
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + angle;
		result = prime * result + controlPower;
		result = prime * result + disturbPower;
		long temp;
		temp = Double.doubleToLongBits(disturbSpeed);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + time;
		return result;
	}

	// eclipse generated equals method
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof BrickState))
			return false;
		BrickState other = (BrickState) obj;
		if (angle != other.angle)
			return false;
		if (controlPower != other.controlPower)
			return false;
		if (disturbPower != other.disturbPower)
			return false;
		if (Double.doubleToLongBits(disturbSpeed) != Double
				.doubleToLongBits(other.disturbSpeed))
			return false;
		if (time != other.time)
			return false;
		return true;
	}

}
