#!/bin/bash
# split a file into 2 files with the 80% and 20% off the
# original file's randomly shuffled lines

if [[ $# -eq 0 ]]
	then
		echo "File arg required"
		exit 1
fi

headFile='train-set.csv'
tailFile='test-set.csv'

if [[ $# -eq 3 ]]
	then 
		headFile=$2
		tailFile=$3
		echo "Using $headFile as train set and $tailFile as test set"
fi

outputFile=$1
lineCount=$(wc -l $outputFile | cut -d' ' -f1)
h=$(expr $lineCount \* 8 / 10)
t=$(expr $lineCount - $h)

rm $headfile $tailFile

# could be optimized
shuf $outputFile | head -$h > $headFile &&
shuf $outputFile | tail -$t > $tailFile &&

echo "Wrote $h lines to $headFile and $t lines to $tailFile"
