#!/bin/bash
if [[ $# -ne 0 ]]; then
	echo "Passing arguments to gen_sse"
	./gen_sse.rb "$@" > ann.c && make & rm weights.net
else
	make
	if [[ $? -eq 0 ]]; then
		lrs=(0.1, 0.001, 0.0001, 0.00001, 0.000001, 0.0000001)
		echo $lrs
		for i in "${lrs[@]}"; do
			./train $i
#			PID=$!
#			kill -INT $PID
		done
	fi
fi
exit 0
